// Bibliothèque de templates de séances (≥ 3 par type, sauf course/runtaf/velotaf).
// Tous les `type` correspondent à WorkoutType (cf. lib/activities/intensity.ts).
// Le type 'seuil_tempo' remplace l'ancien 'seuil' du prompt.

import type { SessionTemplate } from '@/types/plan'

export const SESSION_TEMPLATES: SessionTemplate[] = [
  // === Sortie Longue ===
  {
    id: 'sl-1h30',
    type: 'sortie_longue',
    title: 'SL 1h30 vallonnée',
    defaultDuration: 90,
    defaultDistance: 15,
    defaultElevation: 400,
    defaultIntensity: 2,
    description: 'Endurance fondamentale sur terrain vallonné. Allure conversationnelle.',
    tags: ['endurance', 'base'],
  },
  {
    id: 'sl-2h-progressive',
    type: 'sortie_longue',
    title: 'SL 2h progressive',
    defaultDuration: 120,
    defaultDistance: 20,
    defaultElevation: 500,
    defaultIntensity: 2,
    description: 'Sortie longue avec dernière demi-heure en allure soutenue.',
    tags: ['endurance', 'progressive'],
  },
  {
    id: 'sl-3h-spe',
    type: 'sortie_longue',
    title: 'SL 3h spécifique',
    defaultDuration: 180,
    defaultDistance: 28,
    defaultElevation: 900,
    defaultIntensity: 3,
    description: 'Sortie longue avec relances en côte pour simuler le format course.',
    tags: ['spécifique', 'long'],
  },

  // === Fractionné (VMA) ===
  {
    id: 'fr-6x500',
    type: 'fractionne',
    title: '6×500m VMA',
    defaultDuration: 60,
    defaultDistance: 8,
    defaultIntensity: 5,
    description: '6×500m R=1min15 trot. Allure 95–100% VMA.',
    tags: ['VMA', 'court'],
  },
  {
    id: 'fr-10x400',
    type: 'fractionne',
    title: '10×400m VMA',
    defaultDuration: 65,
    defaultDistance: 9,
    defaultIntensity: 5,
    description: '10×400m R=1min trot. Allure VMA.',
    tags: ['VMA', 'piste'],
  },
  {
    id: 'fr-3x6min',
    type: 'fractionne',
    title: '3×6min allure 5km',
    defaultDuration: 65,
    defaultDistance: 10,
    defaultIntensity: 5,
    description: '3×6min R=2min30. Allure 5km / 92–95% VMA.',
    tags: ['VMA', 'long'],
  },

  // === Seuil / Tempo ===
  {
    id: 'se-3x10',
    type: 'seuil_tempo',
    title: '3×10min Seuil',
    defaultDuration: 65,
    defaultDistance: 11,
    defaultIntensity: 4,
    description: '3×10min allure seuil R=2min trot.',
    tags: ['seuil'],
  },
  {
    id: 'se-2x20',
    type: 'seuil_tempo',
    title: '2×20min Seuil',
    defaultDuration: 75,
    defaultDistance: 13,
    defaultIntensity: 4,
    description: '2×20min allure seuil R=3min trot. Séance clé.',
    tags: ['seuil', 'long'],
  },
  {
    id: 'te-40min',
    type: 'seuil_tempo',
    title: 'Tempo 40min',
    defaultDuration: 60,
    defaultDistance: 11,
    defaultIntensity: 3,
    description: '40min continu allure tempo / seuil bas.',
    tags: ['tempo'],
  },

  // === Côtes ===
  {
    id: 'co-10x30s',
    type: 'cotes',
    title: '10×30s côtes',
    defaultDuration: 55,
    defaultDistance: 8,
    defaultElevation: 200,
    defaultIntensity: 5,
    description: '10×30s côte raide à fond, récup descente trot.',
    tags: ['côtes', 'court', 'puissance'],
  },
  {
    id: 'co-6x2min',
    type: 'cotes',
    title: '6×2min côtes longues',
    defaultDuration: 70,
    defaultDistance: 10,
    defaultElevation: 350,
    defaultIntensity: 4,
    description: '6×2min côte modérée allure seuil, descente trot.',
    tags: ['côtes', 'long', 'seuil'],
  },
  {
    id: 'co-bosses-natu',
    type: 'cotes',
    title: 'Sortie bosses 1h30',
    defaultDuration: 90,
    defaultDistance: 13,
    defaultElevation: 600,
    defaultIntensity: 3,
    description: 'Parcours naturel à bosses, relances libres.',
    tags: ['côtes', 'spécifique'],
  },

  // === Course ===
  {
    id: 'cr-cible',
    type: 'course',
    title: 'Course objectif',
    defaultDuration: 240,
    defaultIntensity: 4,
    description: 'Course cible. Distance, D+ et durée à personnaliser.',
    tags: ['objectif'],
  },
  {
    id: 'cr-prep',
    type: 'course',
    title: 'Course de prépa',
    defaultDuration: 90,
    defaultDistance: 15,
    defaultElevation: 600,
    defaultIntensity: 4,
    description: 'Course intermédiaire en mode test grandeur nature.',
    tags: ['prépa', 'test'],
  },

  // === Runtaf ===
  {
    id: 'rt-aller',
    type: 'runtaf',
    title: 'Runtaf aller (30min)',
    defaultDuration: 30,
    defaultDistance: 5,
    defaultIntensity: 2,
    description: 'Trajet domicile-travail à pied, endurance.',
    tags: ['runtaf', 'transport'],
  },
  {
    id: 'rt-double',
    type: 'runtaf',
    title: 'Runtaf A/R (1h)',
    defaultDuration: 60,
    defaultDistance: 10,
    defaultIntensity: 2,
    description: 'Trajet aller + retour à pied.',
    tags: ['runtaf', 'transport'],
  },

  // === Velotaf ===
  {
    id: 'vt-1h',
    type: 'velotaf',
    title: 'Velotaf 1h',
    defaultDuration: 60,
    defaultDistance: 20,
    defaultIntensity: 2,
    description: 'Trajet vélo modéré, récupération active.',
    tags: ['velotaf', 'transport', 'recup'],
  },

  // === Footing ===
  {
    id: 'ft-30',
    type: 'footing',
    title: 'Footing 30min',
    defaultDuration: 30,
    defaultDistance: 5,
    defaultIntensity: 2,
    description: 'Footing facile, Z2.',
    tags: ['endurance', 'court'],
  },
  {
    id: 'ft-45',
    type: 'footing',
    title: 'Footing 45min',
    defaultDuration: 45,
    defaultDistance: 7.5,
    defaultIntensity: 2,
    description: 'Footing endurance Z2.',
    tags: ['endurance'],
  },
  {
    id: 'ft-1h',
    type: 'footing',
    title: 'Footing 1h',
    defaultDuration: 60,
    defaultDistance: 10,
    defaultIntensity: 2,
    description: 'Footing aérobie 1h plat ou légèrement vallonné.',
    tags: ['endurance', 'aérobie'],
  },
]
