// Mirror of ui/theme/Color.kt — source of truth for all chart and JS color usage.
// For Tailwind className usage, see tailwind.config.ts (trail-* tokens).

export const dark = {
  background:       '#0A0F0E',
  surface:          '#111A18',
  cardBg:           '#162420',
  border:           '#1E3530',
  headerBg:         '#101917',
  subtleText:       '#8BA8A3',
  text:             '#E2ECE9',
  greenOk:          '#4ADE80',
  paleGreen:        '#0A2E1E',
  runRed:           '#F87171',
  bikeBlack:        '#38BDF8',
  chargeOrange:     '#FF7900',
  bikeGreen:        '#27A971',
  swimBlue:         '#4BB4E6',
  seriesBlue:       '#38BDF8',
  seriesRed:        '#F87171',
  seriesOrange:     '#FF7900',
  seriesYellow:     '#FBBF24',
  seriesGreen:      '#4ADE80',
  pieRuntaf:        '#FF7900',
  pieVma:           '#F87171',
  pieSeuil:         '#FBBF24',
  pieCotes:         '#8B5CF6',
  pieSortieLongue:  '#38BDF8',
  pieFooting:       '#4ADE80',
  pieAutre:         '#6B8A85',
  progressRunBg:    '#243530',
  progressRunFg:    '#FF7900',
  progressVolumeBg: '#13211E',
  progressVolumeFg: '#4ADE80',
  progressDPlusBg:  '#11232A',
  progressDPlusFg:  '#38BDF8',
} as const

export const light = {
  background:       '#F4F7F6',
  surface:          '#FFFFFF',
  cardBg:           '#FFFFFF',
  border:           '#D6E1DD',
  headerBg:         '#E8F0ED',
  subtleText:       '#5F7771',
  text:             '#13201D',
  greenOk:          '#138A52',
  paleGreen:        '#DFF5E8',
  runRed:           '#D94F45',
  bikeBlack:        '#1D8FC6',
  chargeOrange:     '#C2410C',
  bikeGreen:        '#1E8E5E',
  swimBlue:         '#2A8FC4',
  seriesBlue:       '#1D8FC6',
  seriesRed:        '#D94F45',
  seriesOrange:     '#C2410C',
  seriesYellow:     '#CC9200',
  seriesGreen:      '#138A52',
  pieRuntaf:        '#C2410C',
  pieVma:           '#D94F45',
  pieSeuil:         '#CC9200',
  pieCotes:         '#7C56C9',
  pieSortieLongue:  '#1D8FC6',
  pieFooting:       '#138A52',
  pieAutre:         '#7B8E88',
  progressRunBg:    '#FBE2D8',
  progressRunFg:    '#C2410C',
  progressVolumeBg: '#DFF5E8',
  progressVolumeFg: '#138A52',
  progressDPlusBg:  '#DCF0F7',
  progressDPlusFg:  '#1D8FC6',
} as const

// Default export — theme-aware tokens. Background-like fields resolve to CSS
// variables so they follow .light / .dark on <html>, while accent/series
// colors stay as fixed hex (used for chart series, opacity math like
// `${color}26`, and other places that can't consume CSS vars).
export const colors = {
  ...dark,
  background: 'var(--trail-bg)',
  surface:    'var(--trail-surface)',
  cardBg:     'var(--trail-card)',
  border:     'var(--trail-border)',
  headerBg:   'var(--trail-header)',
  subtleText: 'var(--trail-muted)',
  text:       'var(--trail-text)',
  paleGreen:  'var(--trail-pale-green)',
} as const

export type TrailPalette = typeof dark
